.PHONY: help up down build logs migrate revision seed backend-dev frontend-dev lint

help:
	@echo "SyncOps AI — common tasks"
	@echo "  make up           # build + start the full stack (db, backend, frontend)"
	@echo "  make down         # stop the stack"
	@echo "  make build        # rebuild images"
	@echo "  make logs         # tail all logs"
	@echo "  make migrate      # run alembic migrations in the backend container"
	@echo "  make revision m=  # create a new autogenerated migration"
	@echo "  make backend-dev  # run backend locally (uv)"
	@echo "  make frontend-dev # run frontend locally (npm)"

up:
	docker compose up -d --build

down:
	docker compose down

build:
	docker compose build

logs:
	docker compose logs -f

migrate:
	docker compose exec backend alembic upgrade head

revision:
	docker compose exec backend alembic revision --autogenerate -m "$(m)"

backend-dev:
	cd backend && uv run uvicorn app.main:app --reload --port 8000

frontend-dev:
	cd frontend && npm run dev

lint:
	cd backend && uv run ruff check .
	cd frontend && npm run lint
